ScheduleMVC_Update/Controllers/APanel/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleMVC_Update.Models;

namespace ScheduleMVC_Update.Controllers
{
    public class ScheduleController : Controller
    {
        private ScheduleContext db = new ScheduleContext();


        // Автодополнение преподавателей
        public ActionResult AutocompleteSearchLecturer(string term)
        {
            var models = db.ScheduleMainSet.Where(a => a.LecturerSet.LecturerFullName.Contains(term))
                            .Select(a => new { value = a.LecturerSet.LecturerFullName })
                            .Distinct();

            return Json(models, JsonRequestBehavior.AllowGet);
        }

        // Автодополнение групп
        public ActionResult AutocompleteSearchGroup(string term)
        {
            var models = db.ScheduleMainSet.Where(a => a.GroupSet.GroupName.Contains(term))
                            .Select(a => new { value = a.GroupSet.GroupName })
                            .Distinct();

            return Json(models, JsonRequestBehavior.AllowGet);
        }

        // GET: Schedule
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var date = DateTime.Now.Date;
            var scheduleMainSet = db.ScheduleMainSet
                                        .Include(s => s.AuditorySet)
                                        .Include(s => s.DisciplineSet)
                                        .Include(s => s.GroupSet)
                                        .Include(s => s.LecturerSet)
                                        .Include(s => s.PairSet)
                                        .OrderBy(x => x.GroupSet.GroupName)
                                        .OrderBy(x => x.DaysOfWeek)
                                        .ToListAsync();
            
            return View(await scheduleMainSet);
        }

        // GET: Schedule/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            ScheduleMainSet scheduleMainSet = await db.ScheduleMainSet.FindAsync(id);

            if (scheduleMainSet == null)
                return HttpNotFound();

            return View(scheduleMainSet);
        }

        // GET: Schedule/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.AuditoryAuditoryId = new SelectList(db.AuditorySet.OrderBy(x => x.AuditoryName), "AuditoryId", "AuditoryName");
            ViewBag.DisciplineDisciplineId = new SelectList(db.DisciplineSet.OrderBy(x => x.TitleDiscipline), "DisciplineId", "TitleDiscipline");
            ViewBag.GroupGroupId = new SelectList(db.GroupSet.OrderBy(x => x.GroupName), "GroupId", "GroupName");
            ViewBag.LecturerLecturerId = new SelectList(db.LecturerSet.OrderBy(x => x.LecturerFullName), "LecturerId", "LecturerFullName");
            ViewBag.PairPairId = new SelectList(db.PairSet.OrderBy(x => x.PairNumber), "PairId", "PairNumber");
            return View();
        }

        // POST: Schedule/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ScheduleId,Date,DisciplineDisciplineId,LecturerLecturerId,GroupGroupId,AuditoryAuditoryId,PairPairId,Annotation,DaysOfWeek")] ScheduleMainSet scheduleMainSet)
        {
            if (ModelState.IsValid)
            {
                db.ScheduleMainSet.Add(scheduleMainSet);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AuditoryAuditoryId = new SelectList(db.AuditorySet, "AuditoryId", "AuditoryName", scheduleMainSet.AuditoryAuditoryId);
            ViewBag.DisciplineDisciplineId = new SelectList(db.DisciplineSet, "DisciplineId", "TitleDiscipline", scheduleMainSet.DisciplineDisciplineId);
            ViewBag.GroupGroupId = new SelectList(db.GroupSet, "GroupId", "GroupName", scheduleMainSet.GroupGroupId);
            ViewBag.LecturerLecturerId = new SelectList(db.LecturerSet, "LecturerId", "LecturerFullName", scheduleMainSet.LecturerLecturerId);
            ViewBag.PairPairId = new SelectList(db.PairSet.OrderBy(x => x.PairNumber), "PairId", "PairNumber", scheduleMainSet.PairPairId);
            return View(scheduleMainSet);
        }

        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduleMainSet scheduleMainSet = await db.ScheduleMainSet.FindAsync(id);
            if (scheduleMainSet == null)
            {
                return HttpNotFound();
            }

            ViewBag.AuditoryAuditoryId = new SelectList(db.AuditorySet.OrderBy(x => x.AuditoryName), "AuditoryId", "AuditoryName", scheduleMainSet.AuditoryAuditoryId);
            ViewBag.DisciplineDisciplineId = new SelectList(db.DisciplineSet.OrderBy(x => x.TitleDiscipline), "DisciplineId", "TitleDiscipline", scheduleMainSet.DisciplineDisciplineId);
            ViewBag.GroupGroupId = new SelectList(db.GroupSet.OrderBy(x => x.GroupName), "GroupId", "GroupName", scheduleMainSet.GroupGroupId);
            ViewBag.LecturerLecturerId = new SelectList(db.LecturerSet.OrderBy(x => x.LecturerFullName), "LecturerId", "LecturerFullName", scheduleMainSet.LecturerLecturerId);
            ViewBag.PairPairId = new SelectList(db.PairSet.OrderBy(x => x.PairNumber), "PairId", "PairNumber", scheduleMainSet.PairPairId);

            return View(scheduleMainSet);
        }

        // POST: Schedule/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ScheduleId,Date,DisciplineDisciplineId,LecturerLecturerId,GroupGroupId,AuditoryAuditoryId,PairPairId,Annotation,DaysOfWeek")] ScheduleMainSet scheduleMainSet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scheduleMainSet).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AuditoryAuditoryId = new SelectList(db.AuditorySet, "AuditoryId", "AuditoryName", scheduleMainSet.AuditoryAuditoryId);
            ViewBag.DisciplineDisciplineId = new SelectList(db.DisciplineSet, "DisciplineId", "TitleDiscipline", scheduleMainSet.DisciplineDisciplineId);
            ViewBag.GroupGroupId = new SelectList(db.GroupSet, "GroupId", "GroupName", scheduleMainSet.GroupGroupId);
            ViewBag.LecturerLecturerId = new SelectList(db.LecturerSet, "LecturerId", "LecturerFullName", scheduleMainSet.LecturerLecturerId);
            ViewBag.PairPairId = new SelectList(db.PairSet, "PairId", "PairNumber", scheduleMainSet.PairPairId);
            return View(scheduleMainSet);
        }

        // GET: Schedule/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduleMainSet scheduleMainSet = await db.ScheduleMainSet.FindAsync(id);
            if (scheduleMainSet == null)
            {
                return HttpNotFound();
            }
            return View(scheduleMainSet);
        }

        // POST: Schedule/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ScheduleMainSet scheduleMainSet = await db.ScheduleMainSet.FindAsync(id);
            db.ScheduleMainSet.Remove(scheduleMainSet);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ScheduleMVC_Update/Controllers/DisciplinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleMVC_Update.Models;

namespace ScheduleMVC_Update.Controllers
{
    public class DisciplinesController : Controller
    {
        private ScheduleContext db = new ScheduleContext();

        // GET: Disciplines
        public async Task<ActionResult> Index()
        {
            return View(await db.DisciplineSet.ToListAsync());
        }

        // GET: Disciplines/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DisciplineSet disciplineSet = await db.DisciplineSet.FindAsync(id);
            if (disciplineSet == null)
            {
                return HttpNotFound();
            }
            return View(disciplineSet);
        }

        // GET: Disciplines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Disciplines/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DisciplineId,TitleDiscipline")] DisciplineSet disciplineSet)
        {
            if (ModelState.IsValid)
            {
                db.DisciplineSet.Add(disciplineSet);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(disciplineSet);
        }

        // GET: Disciplines/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DisciplineSet disciplineSet = await db.DisciplineSet.FindAsync(id);
            if (disciplineSet == null)
            {
                return HttpNotFound();
            }
            return View(disciplineSet);
        }

        // POST: Disciplines/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "DisciplineId,TitleDiscipline")] DisciplineSet disciplineSet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(disciplineSet).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(disciplineSet);
        }

        // GET: Disciplines/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DisciplineSet disciplineSet = await db.DisciplineSet.FindAsync(id);
            if (disciplineSet == null)
            {
                return HttpNotFound();
            }
            return View(disciplineSet);
        }

        // POST: Disciplines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            DisciplineSet disciplineSet = await db.DisciplineSet.FindAsync(id);
            db.DisciplineSet.Remove(disciplineSet);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ScheduleMVC_Update/Controllers/LecturersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScheduleMVC_Update.Models;

namespace ScheduleMVC_Update.Controllers
{
    public class LecturersController : Controller
    {
        private ScheduleContext db = new ScheduleContext();

        // GET: Lecturers
        public async Task<ActionResult> Index()
        {
            return View(await db.LecturerSet.ToListAsync());
        }

        // GET: Lecturers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LecturerSet lecturerSet = await db.LecturerSet.FindAsync(id);
            if (lecturerSet == null)
            {
                return HttpNotFound();
            }
            return View(lecturerSet);
        }

        // GET: Lecturers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Lecturers/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(LecturerSet lecturerSet)
        {
            if (ModelState.IsValid)
            {
                db.LecturerSet.Add(lecturerSet);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(lecturerSet);
        }

        // GET: Lecturers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LecturerSet lecturerSet = await db.LecturerSet.FindAsync(id);
            if (lecturerSet == null)
            {
                return HttpNotFound();
            }
            return View(lecturerSet);
        }

        // POST: Lecturers/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(LecturerSet lecturerSet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lecturerSet).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(lecturerSet);
        }

        // GET: Lecturers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LecturerSet lecturerSet = await db.LecturerSet.FindAsync(id);
            if (lecturerSet == null)
            {
                return HttpNotFound();
            }
            return View(lecturerSet);
        }

        // POST: Lecturers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            LecturerSet lecturerSet = await db.LecturerSet.FindAsync(id);
            db.LecturerSet.Remove(lecturerSet);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ScheduleMVC_Update/Views/Schedule/Index.cshtml
@model IEnumerable<ScheduleMVC_Update.Models.ScheduleMainSet>

@{
    ViewBag.Title = "Список пар";
    var listIsGroup = 0;
    var listIsLecturer = 10000;
}

<h2>Расписание</h2>

<p>
    @Html.ActionLink("Создать новую пару", "Create", null, new { @class = "btn btn-primary" })
</p>
<div>
    <a onclick="hidetxt('list'); return false;" href="#" rel="nofollow">Страницы для редактирование информации</a>
    <div style="display:none;" id="list">
        <br />
        @Html.ActionLink("Страница дисциплин", "Index", "Disciplines", new { area = "" }, new { @class = "btn btn-default" }) |
        @Html.ActionLink("Страница преподавателей", "Index", "Lecturers", new { area = "" }, new { @class = "btn btn-default" }) |
        @Html.ActionLink("Страница групп", "Index", "Groups", new { area = "" }, new { @class = "btn btn-default" }) |
        @Html.ActionLink("Страница аудитории", "Index", "Auditorys", new { area = "" }, new { @class = "btn btn-default" }) |
        @Html.ActionLink("Страница расписания пар", "Index", "Pairs", new { area = "" }, new { @class = "btn btn-default" })
    </div>
</div>

<br />
<div>
    <a onclick="hidetxt('search'); return false;" href="#" rel="nofollow">Страницы индивидуального поиска</a>
    <div style="display:none;" id="search">
        <h2>Поиск по дню недели</h2>
        @using (Html.BeginForm("Index", "ScheduleDayOfWeek", FormMethod.Get, new { @class = "form-inline", role = "form" }))
        {
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span> Поиск по дню недели
                        </button>
                    </span>
                    <input class="form-control text-box single-line"
                           type="text"
                           id="id"
                           required
                           name="id"
                           placeholder="Введите день недели..."
                           title="Четная неделя:Понедельник - 1 Вторник - 2. Нечетная неделя: Понедельник - '-1' Вторник - '-2' " />
                </div>
            </div>
        }
        <p><dfn>*Выводит список всех пар на день недели</dfn></p>
        <hr />

        <h2>Поиск по группе</h2>
        @using (Html.BeginForm("Index", "ScheduleGroups", FormMethod.Get, new { @class = "form-inline", role = "form" }))
        {
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span> Поиск по группе
                        </button>
                    </span>
                    <input class="form-control text-box single-line"
                           type="text"
                           id="id"
                           required
                           name="id"
                           placeholder="Введите номер группы..."
                           pattern="[0-9]{3}-[А-Яа-яЁё]{2}"
                           title="Введите номер группы в формате 421-ТУ"
                           data-autocomplete-source='@Url.Action("AutocompleteSearchGroup", "Schedule")' />
                </div>
            </div>
        }
        <p><dfn>*Выводит список всех пар для конкретной группы</dfn></p>
        <hr />

        <h2>Поиск по преподавателю</h2>
        @using (Html.BeginForm("Index", "ScheduleLecturers", FormMethod.Get, new { @class = "form-inline", role = "form" }))
        {
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span> Поиск по преподавателю
                        </button>
                    </span>
                    <input class="form-control text-box single-line"
                           type="text"
                           id="id"
                           required
                           name="id"
                           placeholder="Введите ФИО преподавателя..."
                           pattern="([А-ЯЁ][а-яё]+[\-\s]?){3,}"
                           title="Введите привильное ФИО..."
                           data-autocomplete-source='@Url.Action("AutocompleteSearchLecturer", "Schedule")' />
                </div>
            </div>
        }
        <p><dfn>*Выводит список всех пар для конкретного преподавателя</dfn></p>
        <hr />

        <h2>Поиск по преподавателю и группе</h2>
        @using (Html.BeginForm("Index", "ScheduleGroupAndLecturer", FormMethod.Get, new { @class = "form-inline", role = "form" }))
        {
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span> Поиск по преподавателю и группе
                        </button>
                    </span>
                    <input class="form-control text-box single-line"
                           type="text"
                           id="idGroup"
                           required
                           name="idGroup"
                           placeholder="Введите номер группы..."
                           pattern="[0-9]{3}-[А-Яа-яЁё]{2}"
                           title="Введите номер группы в формате 421-ТУ"
                           data-autocomplete-source='@Url.Action("AutocompleteSearchGroup", "Schedule")' />
                    <input class="form-control text-box single-line"
                           type="text"
                           id="idLecturer"
                           required
                           name="idLecturer"
                           placeholder="Введите ФИО преподавателя..."
                           pattern="([А-ЯЁ][а-яё]+[\-\s]?){3,}"
                           title="Введите привильное ФИО..."
                           data-autocomplete-source='@Url.Action("AutocompleteSearchLecturer", "Schedule")' />
                </div>
            </div>
        }
        <p><dfn>*Выводит список всех пар для конкретного преподавателя и группы</dfn></p>
        <hr />
    </div>
</div>

<h3 class="text-center">Список всех пар по дням недели</h3>
<div class="row">
    <div class="panel panel-primary filterable">
        <div class="panel-heading">
            <h3 class="panel-title text-center">Список всех пар <br /> </h3>
            <div class="pull-right">
                <button class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-filter"></span> Фильтр</button>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr class="filters">
                        <th><input type="text" class="form-control" placeholder=@Html.DisplayNameFor(model => model.AuditorySet.AuditoryName) disabled></th>
                        <th><input type="text" class="form-control" placeholder=@Html.DisplayNameFor(model => model.DisciplineSet.TitleDiscipline) disabled></th>
                        <th><input type="text" class="form-control" placeholder="Группа" disabled></th>
                        <th><input type="text" class="form-control" placeholder=@Html.DisplayNameFor(model => model.LecturerSet.LecturerFullName) disabled></th>
                        <th><input type="text" class="form-control" placeholder="Номер пары" disabled></th>
                        <th><input type="text" class="form-control" placeholder=@Html.DisplayNameFor(model => model.DaysOfWeek) disabled></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.AuditorySet.AuditoryName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DisciplineSet.TitleDiscipline)
                            </td>
                            <td>
                                <div>
                                    <a onclick="hidetxt('@listIsGroup'); return false;" href="#" rel="nofollow">@Html.DisplayFor(modelItem => item.GroupSet.GroupName)</a>
                                    <div style="display:none;" id="@listIsGroup">
                                        <p>Староста: @Html.DisplayFor(modelItem => item.GroupSet.MonitorOfTheTeam)</p>
                                        <p>Телефон:<a href="tel:@Html.DisplayFor(modelItem => item.GroupSet.MonitorTel)">@Html.DisplayFor(modelItem => item.GroupSet.MonitorTel)</a></p>
                                        <p>Email:<a href="mailto:@Html.DisplayFor(modelItem => item.GroupSet.MonitorEmail)">@Html.DisplayFor(modelItem => item.GroupSet.MonitorEmail)</a></p>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div>
                                    <a onclick="hidetxt('@listIsLecturer'); return false;" href="#" rel="nofollow">@Html.DisplayFor(modelItem => item.LecturerSet.LecturerFullName)</a>
                                    <div style="display:none;" id="@listIsLecturer">
                                        <p>Телефон:<a href="tel:@Html.DisplayFor(modelItem => item.LecturerSet.Phone)">@Html.DisplayFor(modelItem => item.LecturerSet.Phone)</a></p>
                                        <p>Email:<a href="mailto:@Html.DisplayFor(modelItem => item.LecturerSet.Email)">@Html.DisplayFor(modelItem => item.LecturerSet.Email)</a></p>
                                    </div>
                                </div>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PairSet.PairNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DaysOfWeek)
                            </td>
                            <td class="col-lg-3">
                                @Html.ActionLink("Изменить", "Edit", new { id = item.ScheduleId }) |
                                @Html.ActionLink("Подробнее", "Details", new { id = item.ScheduleId }) |
                                @Html.ActionLink("Удалить", "Delete", new { id = item.ScheduleId })
                            </td>
                        </tr>
                        listIsGroup++;
                        listIsLecturer++;
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        $('.filterable .btn-filter').click(function () {
            var $panel = $(this).parents('.filterable'),
            $filters = $panel.find('.filters input'),
            $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function (e) {
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
            inputContent = $input.val().toLowerCase(),
            $panel = $input.parents('.filterable'),
            column = $panel.find('.filters th').index($input.parents('th')),
            $table = $panel.find('.table'),
            $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function () {
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="' + $table.find('.filters th').length + '">No result found</td></tr>'));
            }
        });
    });

    $(function () {
        $("[data-autocomplete-source]").each(function () {
            var target = $(this);
            target.autocomplete({
                source: target.attr("data-autocomplete-source")
            });
        });
    });

    $("#onlyGroup").removeAttr("novalidate");

    var show;
    function hidetxt(type) {
        param = document.getElementById(type);
        if (param.style.display == "none") {
            if (show) show.style.display = "none";
            param.style.display = "block";
            show = param;
        } else param.style.display = "none"
    }
</script>